init:
	pip3 install -r requirements.txt

test:
	nosetests tests

download:
	curl -L -o ratings.txt https://raw.githubusercontent.com/JDonini/depaulmovie-recommender-system/master/dataset/Movie_DePaulMovie/ratings.txt
